name: go-lang-ci-workflows
on: 
  pull_request:
    branches:
      - develop
      - main
jobs:
  check-application:
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    go: ['1.14', '1.15']
    steps:
      #  go-version: ${{matrix.go}}
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Setup Go environment
        uses: actions/setup-go@v3
        with: 

      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
      - 
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - 
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.4.1
      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: juniorcardoso1506/golangci_learn:latest
          
      - run: go test
      - run: go run main.go
    